### ISSUE TITLE
Need more explanation.

### ISSUE THREAD

**Issue by ozgurgunes** [MichalKarol/dropboxignore#1]
This is a feature I'm anticipating very much. I'm doing this manually by selective sync for every project, especially for `node_modules` folder.

Readme file needs a bit more explanation. Where should I create `.dropboxignore` file for example. In Dropbox root or in project folders?

Could you explain more please.

Thanks a lot.

**Comment by MichalKarol** [comment]
Hi, 
Could you take a look into [modified README](https://github.com/MichalKarol/dropboxignore/blob/issue-1/README.md) and provide feedback if more information is needed, and if so what kind of information would you like to see.

**Comment by ozgurgunes** [comment]
Thats great. Thanks.

**Comment by MichalKarol** [comment]
Deployed
